name: CDK8s Synth for Go

on:
  push:
    branches:
      - master
    paths:
      - 'main.go'
      - '.github/workflows/ci-cdk8s-synth.yaml'

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Initialize Go module temporarily
        run: |
          # Initialize go.mod file temporarily for dependency management
          echo "module temp" > go.mod
          echo "go 1.23" >> go.mod
          
      - name: Install all necessary Go dependencies, including indirect ones
        run: |
          # Install all necessary Go dependencies, including indirect ones
          go get github.com/aws/constructs-go/constructs/v10@v10.0.0
          go get github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2@v2.69.0
          go get github.com/cdk8s-team/cdk8s-plus-go/cdk8splus26/v2@v2.69.0
          go get github.com/aws/jsii-runtime-go@v1.53.0
          go get github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2/pkg/apis/meta/v1

      - name: Install CDK8s CLI (for Synthesis)
        run: npm install -g cdk8s-cli

      - name: Run the Go application and synthesize Kubernetes YAML
        run: |
          mkdir -p temp-synth-output
          go run main.go > temp-synth-output/synthesized_output.yaml
          echo "Synthesis complete!"

      - name: Commit synthesized files (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "lingammani2@gmail.com"
          git config --global user.name "rushimanikantalingam"
          git add helm/go-web-app-chart/templates/synth-*
          git commit -m "Add/update synthesized Kubernetes YAML using CDK8s" || echo "No changes to commit"
          git pull origin main --rebase
          git push

      - name: Clean up go.mod file
        run: |
          # Remove the temporary go.mod file after installation
          rm go.mod
