name: CDK8s Synth for Go

on:
  push:
    branches:
      - master
    paths:
      - 'main.go'
      - '.github/workflows/ci-cdk8s-synth.yaml'

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8

      - name: Install Go dependencies
        run: |
          # Create a temporary go.mod to resolve dependencies
          echo "module main" > go.mod
          echo "go 1.23" >> go.mod
          echo "require github.com/aws/constructs-go/constructs/v10 v10.0.0" >> go.mod
          echo "require github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2 v2.69.65" >> go.mod
          echo "require github.com/cdk8s-team/cdk8s-plus-go/cdk8splus26/v2 v2.69.65" >> go.mod

          # Install the dependencies
          go mod tidy
          go get github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2@latest
          go get github.com/cdk8s-team/cdk8s-plus-go/cdk8splus26/v2@latest
          go get github.com/aws/constructs-go/constructs/v10@latest

      - name: Install CDK8s CLI (for Synthesis)
        run: npm install -g cdk8s-cli

      - name: Synthesize Kubernetes YAML using CDK8s
        run: |
          mkdir -p temp-synth-output
          cdk8s synth --app "go run main.go" --output temp-synth-output

      - name: Copy synthesized files to Helm chart (preserving existing files)
        run: |
          for file in temp-synth-output/*.k8s.yaml; do
            name=$(basename "$file")
            cp "$file" "helm/go-web-app-chart/templates/synth-${name}"
          done

      - name: Commit synthesized files (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "lingammani2@gmail.com"
          git config --global user.name "rushimanikantalingam"
          git add helm/go-web-app-chart/templates/synth-*
          git commit -m "Add/update synthesized Kubernetes YAML using CDK8s" || echo "No changes to commit"
          git pull origin main --rebase
          git push
